### ISSUE TITLE
Add \f escape in string constants back into vallang StandardTextReader

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/vallang#270] opened 2024-09-04 08:15 UTC
@jurgenvinju I've fixed 2 bugs I found, and made an extra test case. But I think we have to bring back the escape code. as letting vallang take care breaks support for `\f`. Maybe we should add `\f` support in vallang?

_Originally posted by @DavyLandman in https://github.com/usethesource/rascal/issues/2010#issuecomment-2312527282_

**Comment by DavyLandman** [comment] 2024-09-04 08:19
@jurgenvinju duplicate of: #268

**Closed** 2024-09-06 11:11 UTC
Labels: bug
